### ISSUE TITLE
Horizontal Slider should always display the same scroll size

### ISSUE THREAD

**Issue by jens-maus** [amiga-mui/texteditor#9]
After having implemented the horizontal slider functionality I quickly tested it and recognized that it is currently implemented in a non-standard way horizontal slider are usually working in text editors.

As an example, start `TextEditor-Test`. It contains a very long line at the very top which causes the horizontal slider to automatically reduce to a very small size showing a user that there is lot of text to be scrolled to the right. If you now move the vertical slider down so that the very long line disappears from the field of view (FOV) the horizontal slider adapts itself to a different size because all the current lines in the FOV are not scrollable so much to the right like the top line.

This is quite a non-standard way of displaying/handling sliders in a text editor. I would like to therefore request that the horizontal slider functionality should be changed so that the slider size is only dependent on the maximum length of a line within the WHOLE text and not just within the current FOV.

**Comment by jens-maus** [comment]
@alpyre 
Can you please take care of implementing this functionality ASAP? Thanks.

**Comment by alpyre** [comment]
I am returning home now, I'll reflect on the issue in half an hour.

2016-10-27 15:43 GMT+03:00 Jens Maus <notifications@github.com>:

**Comment by alpyre** [comment]
You are totally correct about the "standard way" of doing horizontal scrolling.

But I belive that the way I've implemented it is more a **"MUI" way** of doing it. You'll understand what I mean by that if you just open your YAM and scroll up and down your incoming listview while keeping an eye on the horizontal scroller it has.

Actually, it would be much much easier to code it for the standard behaviour. I really spent a lot of time to cover this MUI like behaviour.

But I understand your point. Our implementation **must** cover the modern, standard behaviour as well (fortunately, with the current implementation, I can get there by only 2 or 3 modifications here'n there).  

So I'd like to suggest a new public attribute like **MUIA_TextEditor_Slider_Behaviour** along with the values:
**MUIV_TextEditor_Slider_Standard**
**MUIV_TextEditor_Slider_MUI**
...so that the developer can decide which way it wants it to behave.

We can make the Standard behaviour as default if you wish.

**Comment by alpyre** [comment]
@jens-maus 
Pull request #10 will handle this issue.
Regards.

**Comment by jens-maus** [comment]
@alpyre 
Sorry, but this pull request is invalid. You forgot to pull the recent changes I did in the main repository of TextEditor.mcc before applying new changes. So please remove your fork again and create a new one right from the current state of the TE.mcc repository. Then apply your changes for the Horizontal slider again and create a new pull request. Simply see the diff in the pull request. It not only shows your new changes but again all the old changes to actually implement HSlider support at all.

And of course it would be great if you could actually consider using git directly rather than the GitHub desktop feature ;)

**Comment by jens-maus** [comment]
And let me comment here on your own comments regarding the "standard" way of doing horizontal scrolling.

I don't know which "MUI" way are you referring to (the mail list in YAM is actually using NList - but this is something completely different), but for a TextEditor there is actually only one way of displaying a horizontal slider content size and that's how I have initially stated. I don't really see why a TextEditor should resize itself based on the field of view only. A text editor more or less displays a paper someone has written on and if you scroll down the paper size doesn't really change and is still defined to be as large as the longest line on the whole paper. So I don't really see a benefit in adding MUIA_TextEditor_Slider_Behaviour to allow developers to have a horizontal slider being recalculated upon scrolling up&down. So please revert your change and make the HSlider to always show the same size no matter where I scroll up&down.

**Comment by alpyre** [comment]
A valid PR #11 created.
I kept the MUIA_TextEditor_Slider_Behaviour attribute **private**.
So developers that stick to the doc file won't know about it.

I hope we can compromise on this. :)
